import {
  pgTable,
  uuid,
  text,
  timestamp,
  varchar,
  integer,
  boolean,
  jsonb,
  time,
  date,
} from 'drizzle-orm/pg-core';
import { relations } from 'drizzle-orm';
import { users } from './users.schema';
import { workspace } from './workspace.schema';
import { posts } from './posts.schema';

// =============================================================================
// Drip Campaign Status
// =============================================================================
export const DRIP_STATUSES = [
  'draft',           // Not yet activated
  'active',          // Running and generating posts
  'paused',          // Temporarily paused by user
  'completed',       // All occurrences completed
  'cancelled',       // Cancelled by user
  'error',           // Stopped due to errors
] as const;

export type DripStatus = (typeof DRIP_STATUSES)[number];

// =============================================================================
// Drip Occurrence Types
// =============================================================================
export const OCCURRENCE_TYPES = [
  'daily',           // Every day
  'weekly',          // Specific days of week
  'custom',          // Custom interval in days
] as const;

export type OccurrenceType = (typeof OCCURRENCE_TYPES)[number];

// =============================================================================
// Drip Post Status (individual scheduled post within a drip)
// =============================================================================
export const DRIP_POST_STATUSES = [
  'pending',         // Waiting to be generated by AI
  'generating',      // AI is currently generating content
  'pending_review',  // Generated, waiting for user review
  'approved',        // User approved (or auto-approved after review window)
  'scheduled',       // Scheduled in BullMQ, ready to publish
  'publishing',      // Currently being published
  'published',       // Successfully published
  'failed',          // Failed to publish
  'skipped',         // Skipped by user or system
  'cancelled',       // Cancelled
] as const;

export type DripPostStatus = (typeof DRIP_POST_STATUSES)[number];

// =============================================================================
// 1. Drip Campaigns - Main table for drip configurations
// =============================================================================
export const dripCampaigns = pgTable('drip_campaigns', {
  id: uuid('id').defaultRandom().primaryKey(),
  workspaceId: uuid('workspace_id')
    .notNull()
    .references(() => workspace.id, { onDelete: 'cascade' }),
  createdById: uuid('created_by_id')
    .notNull()
    .references(() => users.id, { onDelete: 'set null' }),

  // Campaign details
  name: varchar('name', { length: 255 }).notNull(),
  description: text('description'),

  // AI Configuration
  aiEnabled: boolean('ai_enabled').default(true).notNull(),
  niche: varchar('niche', { length: 255 }).notNull(), // e.g., "Tech News", "Crypto", "Fitness"
  additionalPrompt: text('additional_prompt'), // Extra instructions for AI
  tone: varchar('tone', { length: 50 }).default('professional'), // professional, casual, humorous, etc.
  language: varchar('language', { length: 10 }).default('en'), // en, es, fr, etc.

  // Target channels (JSON array of channel IDs)
  targetChannelIds: jsonb('target_channel_ids').$type<string[]>().notNull(),

  // Schedule configuration
  occurrenceType: varchar('occurrence_type', { length: 20 }).notNull(), // daily, weekly, custom
  publishTime: time('publish_time').notNull(), // Time to publish (e.g., "09:00:00")
  timezone: varchar('timezone', { length: 50 }).default('UTC').notNull(),

  // For weekly: which days (0=Sunday, 1=Monday, etc.)
  weeklyDays: jsonb('weekly_days').$type<number[]>().default([]),

  // For custom: interval in days
  customIntervalDays: integer('custom_interval_days'),

  // Duration
  startDate: date('start_date').notNull(),
  endDate: date('end_date').notNull(),

  // AI generation timing (minutes before publish time)
  aiGenerationLeadTime: integer('ai_generation_lead_time').default(60).notNull(), // 60 minutes = 1 hour
  emailNotificationLeadTime: integer('email_notification_lead_time').default(30).notNull(), // 30 minutes

  // Auto-approve settings
  autoApprove: boolean('auto_approve').default(false).notNull(), // If true, skip review window

  // Status tracking
  status: varchar('status', { length: 20 }).default('draft').notNull(),
  totalOccurrences: integer('total_occurrences').default(0).notNull(),
  completedOccurrences: integer('completed_occurrences').default(0).notNull(),
  failedOccurrences: integer('failed_occurrences').default(0).notNull(),

  // Error tracking
  lastError: text('last_error'),
  lastErrorAt: timestamp('last_error_at'),
  consecutiveErrors: integer('consecutive_errors').default(0).notNull(),
  maxConsecutiveErrors: integer('max_consecutive_errors').default(3).notNull(), // Pause after X errors

  // Metadata
  metadata: jsonb('metadata').$type<Record<string, any>>().default({}),

  // Timestamps
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
  activatedAt: timestamp('activated_at'),
  pausedAt: timestamp('paused_at'),
  completedAt: timestamp('completed_at'),
});

// =============================================================================
// 2. Drip Posts - Individual posts within a drip campaign
// =============================================================================
export const dripPosts = pgTable('drip_posts', {
  id: uuid('id').defaultRandom().primaryKey(),
  dripCampaignId: uuid('drip_campaign_id')
    .notNull()
    .references(() => dripCampaigns.id, { onDelete: 'cascade' }),

  // Occurrence tracking
  occurrenceNumber: integer('occurrence_number').notNull(), // 1, 2, 3, ...
  scheduledDate: date('scheduled_date').notNull(), // The date this post is for
  scheduledTime: time('scheduled_time').notNull(), // Time to publish
  scheduledAt: timestamp('scheduled_at').notNull(), // Full timestamp (date + time + timezone)

  // AI generation timing
  aiGenerationAt: timestamp('ai_generation_at').notNull(), // When AI should generate
  emailNotificationAt: timestamp('email_notification_at').notNull(), // When to send email

  // Status
  status: varchar('status', { length: 20 }).default('pending').notNull(),

  // Generated content (populated by AI)
  generatedContent: text('generated_content'),

  // Platform-specific content (AI generates different content per platform)
  platformContent: jsonb('platform_content').$type<Record<string, {
    text: string;
    hashtags?: string[];
    mediaUrls?: string[];
  }>>().default({}),

  // Search results used for generation (for transparency)
  searchResults: jsonb('search_results').$type<{
    query: string;
    results: Array<{
      title: string;
      url: string;
      snippet: string;
    }>;
    // Images fetched from web search (related to the niche/news)
    images?: Array<{
      url: string;
      description?: string;
    }>;
    searchedAt: string;
  }>(),

  // Link to actual post (after creation)
  postId: uuid('post_id').references(() => posts.id, { onDelete: 'set null' }),

  // BullMQ job IDs for tracking
  aiGenerationJobId: varchar('ai_generation_job_id', { length: 100 }),
  emailNotificationJobId: varchar('email_notification_job_id', { length: 100 }),
  publishJobId: varchar('publish_job_id', { length: 100 }),

  // User review
  reviewedAt: timestamp('reviewed_at'),
  reviewedById: uuid('reviewed_by_id').references(() => users.id),
  userEdits: jsonb('user_edits').$type<{
    originalContent: string;
    editedContent: string;
    editedAt: string;
  }>(),

  // Error tracking
  lastError: text('last_error'),
  lastErrorAt: timestamp('last_error_at'),
  retryCount: integer('retry_count').default(0).notNull(),
  maxRetries: integer('max_retries').default(3).notNull(),

  // Timestamps
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
  generatedAt: timestamp('generated_at'),
  publishedAt: timestamp('published_at'),
});

// =============================================================================
// 3. Drip Campaign History - Audit log for all actions
// =============================================================================
export const dripCampaignHistory = pgTable('drip_campaign_history', {
  id: uuid('id').defaultRandom().primaryKey(),
  dripCampaignId: uuid('drip_campaign_id')
    .notNull()
    .references(() => dripCampaigns.id, { onDelete: 'cascade' }),
  dripPostId: uuid('drip_post_id').references(() => dripPosts.id, { onDelete: 'set null' }),

  action: varchar('action', { length: 50 }).notNull(), // created, activated, paused, generated, published, etc.
  previousStatus: varchar('previous_status', { length: 20 }),
  newStatus: varchar('new_status', { length: 20 }),

  performedById: uuid('performed_by_id').references(() => users.id),
  performedBySystem: boolean('performed_by_system').default(false).notNull(),

  details: jsonb('details').$type<Record<string, any>>(),
  errorMessage: text('error_message'),

  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// =============================================================================
// Relations
// =============================================================================
export const dripCampaignsRelations = relations(dripCampaigns, ({ one, many }) => ({
  workspace: one(workspace, {
    fields: [dripCampaigns.workspaceId],
    references: [workspace.id],
  }),
  createdBy: one(users, {
    fields: [dripCampaigns.createdById],
    references: [users.id],
  }),
  dripPosts: many(dripPosts),
  history: many(dripCampaignHistory),
}));

export const dripPostsRelations = relations(dripPosts, ({ one }) => ({
  dripCampaign: one(dripCampaigns, {
    fields: [dripPosts.dripCampaignId],
    references: [dripCampaigns.id],
  }),
  post: one(posts, {
    fields: [dripPosts.postId],
    references: [posts.id],
  }),
  reviewedBy: one(users, {
    fields: [dripPosts.reviewedById],
    references: [users.id],
  }),
}));

export const dripCampaignHistoryRelations = relations(dripCampaignHistory, ({ one }) => ({
  dripCampaign: one(dripCampaigns, {
    fields: [dripCampaignHistory.dripCampaignId],
    references: [dripCampaigns.id],
  }),
  dripPost: one(dripPosts, {
    fields: [dripCampaignHistory.dripPostId],
    references: [dripPosts.id],
  }),
  performedBy: one(users, {
    fields: [dripCampaignHistory.performedById],
    references: [users.id],
  }),
}));

// =============================================================================
// Type Exports
// =============================================================================
export type DripCampaign = typeof dripCampaigns.$inferSelect;
export type NewDripCampaign = typeof dripCampaigns.$inferInsert;

export type DripPost = typeof dripPosts.$inferSelect;
export type NewDripPost = typeof dripPosts.$inferInsert;

export type DripCampaignHistoryEntry = typeof dripCampaignHistory.$inferSelect;
export type NewDripCampaignHistoryEntry = typeof dripCampaignHistory.$inferInsert;
