-- Baseline: record migrations already applied to production BY HAND,
-- WITHOUT running them. Equivalent to:
--   npm run db:baseline -- --upto 0035_error_logs.sql
-- but runnable from the Railway Postgres console, which has psql but no node.
--
-- Checksums are generated by the runner's own checksumOf() (sha256 of the file
-- with CRLF normalised to LF), so they match what the container will compute.
--
-- Safe to run twice: ON CONFLICT DO NOTHING.
-- Creates NO schema and runs NONE of these migrations.

BEGIN;

CREATE TABLE IF NOT EXISTS applied_migrations (
  name        varchar(255) PRIMARY KEY,
  checksum    varchar(64)  NOT NULL,
  applied_at  timestamptz  NOT NULL DEFAULT now()
);

INSERT INTO applied_migrations (name, checksum) VALUES
  ('0000_gifted_james_howlett.sql', '2947f932f5d6fa42b84c2ab116338b2dcc24a6e4056e0ed465f6c20824c73d0e'),
  ('0001_motionless_big_bertha.sql', 'ac40bd6af1d1a5c806a93698669d51f5a50812df1de8b54682b8ea109cf3436c'),
  ('0002_hot_lethal_legion.sql', '8208adbb3e6bbb6cd2fa8524c96482b26aff1bd678da933a4fa76354d39370bc'),
  ('0003_ordinary_thena.sql', 'e334efcddd0a5a9091c79ad01981c9d9d9c63ae6bf308f6f11f922fa379ce04e'),
  ('0004_certain_piledriver.sql', 'a7134193e098144e742407c727534c4217aaadf4b4544daa32f6e955d3bce993'),
  ('0005_sad_scalphunter.sql', 'ede610336be96564f0d591355ea20b960ba9b619ac933693e700bcd248c1bd69'),
  ('0006_wandering_moira_mactaggert.sql', '2a3090370810deacc214ad0df963e988f950d9a625e6801e1f2f03f5b5752358'),
  ('0007_dashing_brother_voodoo.sql', 'e1fdbd04417a5d51c805ece63cbfd3840a354ef767db87b96fff1090a288a607'),
  ('0008_bumpy_pepper_potts.sql', 'da9629171ed9370d356125b68d17a070f9eda947fad70a6365129637e8ca8acb'),
  ('0009_round_sabra.sql', 'd851a901f6f18df8943957001fc4a7144c2094d788cc94c976c45017eede50ae'),
  ('0010_puzzling_carnage.sql', '9b0393c9fe4dc2121ed1647b48a2d89907787f1b5cff9664c5464f54fabf6811'),
  ('0011_smart_wolf_cub.sql', '2f3d234714af33eec019ce826c710c0342b6e6d569d3181ccff2483357431001'),
  ('0012_plain_agent_brand.sql', '80935490f12dfaa57baaa0e1a795b17f5a3d5e5d3516aced833223cc67339317'),
  ('0013_clean_menace.sql', 'adc968f114df8434c4483b2c08917d96159384ff39a9bb76333e5c9d4989ca67'),
  ('0014_bored_stranger.sql', '6fc23c2ad0a1b47539f0adab73ffa88006cf1cd4b1bc1823c70b2129cd5656ed'),
  ('0015_wise_lady_vermin.sql', '42442d82ff715b7dcea07102aadb439883e994b56cbc3fdc35e49822a7b2846a'),
  ('0016_great_multiple_man.sql', '06129d5a4a567abe0378ce79f9d2cb7b04596d1bace6564a10fa963c989e54f0'),
  ('0017_marvelous_roxanne_simpson.sql', '08db485a10e1be39d55efd64c6fbe391e36a28bb2c1f3d87cee8db9a96483056'),
  ('0018_tough_luminals.sql', '3942296cb1ad0900c163020a9a7593fe19a0f7e455a5ae8afcc869db15795953'),
  ('0019_harsh_whistler.sql', '15e7dfb65431f35838f95d145a729f7d5a85d69ea2ff4c4e475c738c9de5e548'),
  ('0020_absurd_ken_ellis.sql', '524309e60fe67477df18d0b41fc2470477a7bb722761a72c53fe8bce518399c5'),
  ('0021_old_machine_man.sql', 'be77a83e988fc5e4d7a3e20b48f15abca695a8e857cf7f940b4b72b0b1b03498'),
  ('0022_simple_madame_web.sql', '5d8aac7e2abf242ea5f9cc956c7162b5fcb854ebd66f70b5ca8bbcd0b9ef5d24'),
  ('0023_large_wallop.sql', '24b665eb7631fd5688a5bd0eb4876be4787763a5d7cf73967884deafb81ad956'),
  ('0024_admin_login_challenges.sql', '6e0d937ea122c070301a2a516e74193fa4818c0dda679f2f8e9915738cbdf103'),
  ('0025_feedback_type.sql', '2580e6273b0927abe8bc15ce88cdcc555492ddb10ec3cfbf2d94a7f59836b79a'),
  ('0026_recurring_feedback.sql', 'ef6316c2809568318a47b2f58ec42f3685cf47ae00296539b7c6fea4911b8f77'),
  ('0027_whatsapp_templates.sql', '8984a607f2d54fb85074198616e51678a2da8bc65590c7b1084d1a7e2665d75d'),
  ('0028_maestro_byok.sql', '973f3c6146cdf89789952e777a879e1022f6a85dff0f2452a0b7eefca4d1416e'),
  ('0029_maestro_tone.sql', 'bb94ed805f33d1734ccda804d2e90d9a39089839cd13ca9e7311758d027abea6'),
  ('0030_billing_account_scope.sql', '7d30ffe2a1747c4dbcdc8e5f3cb51fbe9def6490d566b9a3e61b35a5035d55a6'),
  ('0031_backfill_ai_token_reset_date.sql', 'a8af9a4d149d1ccac8f8794307dc3f2b80c4658ae3714f7fa691352a4d0298f6'),
  ('0032_provider_subscriptions.sql', '1ddebbe30626163705122bce6438d71089f6fd585f363a52e48fa40fe4af282d'),
  ('0033_provider_prices.sql', 'e1c92892df2095080579208fe93c9a11ef5c8024f1d514823ad6aacdaa97a778'),
  ('0034_backfill_provider_subscriptions_base_plan.sql', '230dec655fe0c925a935b1f07f29ed1767ba9c119f5253d79f141e26618a4149'),
  ('0035_error_logs.sql', '2b2be923d0782599d6e6d6a80d8483ee4a65c10002d8fb2b0e7a51cdf5dee6e5')
ON CONFLICT (name) DO NOTHING;

COMMIT;

-- Expect 36. If this is not 36, STOP and do not deploy.
SELECT count(*) AS recorded FROM applied_migrations;
